(cl:defpackage assignment2_ros1-srv
  (:use )
  (:export
   "GENERATEPOINT"
   "<GENERATEPOINT-REQUEST>"
   "GENERATEPOINT-REQUEST"
   "<GENERATEPOINT-RESPONSE>"
   "GENERATEPOINT-RESPONSE"
   "USERINPUT"
   "<USERINPUT-REQUEST>"
   "USERINPUT-REQUEST"
   "<USERINPUT-RESPONSE>"
   "USERINPUT-RESPONSE"
  ))

