// Generated by gencpp from file assignment2_ros1/GeneratePointResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINTRESPONSE_H
#define ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_ros1
{
template <class ContainerAllocator>
struct GeneratePointResponse_
{
  typedef GeneratePointResponse_<ContainerAllocator> Type;

  GeneratePointResponse_()
    : x(0.0)
    , y(0.0)  {
    }
  GeneratePointResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GeneratePointResponse_

typedef ::assignment2_ros1::GeneratePointResponse_<std::allocator<void> > GeneratePointResponse;

typedef boost::shared_ptr< ::assignment2_ros1::GeneratePointResponse > GeneratePointResponsePtr;
typedef boost::shared_ptr< ::assignment2_ros1::GeneratePointResponse const> GeneratePointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator1> & lhs, const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator1> & lhs, const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_ros1/GeneratePointResponse";
  }

  static const char* value(const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneratePointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_ros1::GeneratePointResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINTRESPONSE_H
