// Generated by gencpp from file assignment2_ros1/GeneratePoint.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINT_H
#define ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINT_H

#include <ros/service_traits.h>


#include <assignment2_ros1/GeneratePointRequest.h>
#include <assignment2_ros1/GeneratePointResponse.h>


namespace assignment2_ros1
{

struct GeneratePoint
{

typedef GeneratePointRequest Request;
typedef GeneratePointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneratePoint
} // namespace assignment2_ros1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment2_ros1::GeneratePoint > {
  static const char* value()
  {
    return "d650ed2bf3c6f91efef5a89f74343ac5";
  }

  static const char* value(const ::assignment2_ros1::GeneratePoint&) { return value(); }
};

template<>
struct DataType< ::assignment2_ros1::GeneratePoint > {
  static const char* value()
  {
    return "assignment2_ros1/GeneratePoint";
  }

  static const char* value(const ::assignment2_ros1::GeneratePoint&) { return value(); }
};


// service_traits::MD5Sum< ::assignment2_ros1::GeneratePointRequest> should match
// service_traits::MD5Sum< ::assignment2_ros1::GeneratePoint >
template<>
struct MD5Sum< ::assignment2_ros1::GeneratePointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_ros1::GeneratePoint >::value();
  }
  static const char* value(const ::assignment2_ros1::GeneratePointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_ros1::GeneratePointRequest> should match
// service_traits::DataType< ::assignment2_ros1::GeneratePoint >
template<>
struct DataType< ::assignment2_ros1::GeneratePointRequest>
{
  static const char* value()
  {
    return DataType< ::assignment2_ros1::GeneratePoint >::value();
  }
  static const char* value(const ::assignment2_ros1::GeneratePointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment2_ros1::GeneratePointResponse> should match
// service_traits::MD5Sum< ::assignment2_ros1::GeneratePoint >
template<>
struct MD5Sum< ::assignment2_ros1::GeneratePointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_ros1::GeneratePoint >::value();
  }
  static const char* value(const ::assignment2_ros1::GeneratePointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_ros1::GeneratePointResponse> should match
// service_traits::DataType< ::assignment2_ros1::GeneratePoint >
template<>
struct DataType< ::assignment2_ros1::GeneratePointResponse>
{
  static const char* value()
  {
    return DataType< ::assignment2_ros1::GeneratePoint >::value();
  }
  static const char* value(const ::assignment2_ros1::GeneratePointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT2_ROS1_MESSAGE_GENERATEPOINT_H
