// Generated by gencpp from file assignment2_ros1/UserInputResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_ROS1_MESSAGE_USERINPUTRESPONSE_H
#define ASSIGNMENT2_ROS1_MESSAGE_USERINPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_ros1
{
template <class ContainerAllocator>
struct UserInputResponse_
{
  typedef UserInputResponse_<ContainerAllocator> Type;

  UserInputResponse_()
    : success(false)  {
    }
  UserInputResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UserInputResponse_

typedef ::assignment2_ros1::UserInputResponse_<std::allocator<void> > UserInputResponse;

typedef boost::shared_ptr< ::assignment2_ros1::UserInputResponse > UserInputResponsePtr;
typedef boost::shared_ptr< ::assignment2_ros1::UserInputResponse const> UserInputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_ros1::UserInputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_ros1::UserInputResponse_<ContainerAllocator1> & lhs, const ::assignment2_ros1::UserInputResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_ros1::UserInputResponse_<ContainerAllocator1> & lhs, const ::assignment2_ros1::UserInputResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::assignment2_ros1::UserInputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_ros1/UserInputResponse";
  }

  static const char* value(const ::assignment2_ros1::UserInputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::assignment2_ros1::UserInputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserInputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_ros1::UserInputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_ros1::UserInputResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_ROS1_MESSAGE_USERINPUTRESPONSE_H
