// Generated by gencpp from file assignment2_ros1/UserInputRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_ROS1_MESSAGE_USERINPUTREQUEST_H
#define ASSIGNMENT2_ROS1_MESSAGE_USERINPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_ros1
{
template <class ContainerAllocator>
struct UserInputRequest_
{
  typedef UserInputRequest_<ContainerAllocator> Type;

  UserInputRequest_()
    : user_input(0)  {
    }
  UserInputRequest_(const ContainerAllocator& _alloc)
    : user_input(0)  {
  (void)_alloc;
    }



   typedef int64_t _user_input_type;
  _user_input_type user_input;





  typedef boost::shared_ptr< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UserInputRequest_

typedef ::assignment2_ros1::UserInputRequest_<std::allocator<void> > UserInputRequest;

typedef boost::shared_ptr< ::assignment2_ros1::UserInputRequest > UserInputRequestPtr;
typedef boost::shared_ptr< ::assignment2_ros1::UserInputRequest const> UserInputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_ros1::UserInputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_ros1::UserInputRequest_<ContainerAllocator1> & lhs, const ::assignment2_ros1::UserInputRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_input == rhs.user_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_ros1::UserInputRequest_<ContainerAllocator1> & lhs, const ::assignment2_ros1::UserInputRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "219983341b37e0e830bb7bc06656544f";
  }

  static const char* value(const ::assignment2_ros1::UserInputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x219983341b37e0e8ULL;
  static const uint64_t static_value2 = 0x30bb7bc06656544fULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_ros1/UserInputRequest";
  }

  static const char* value(const ::assignment2_ros1::UserInputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 user_input\n"
;
  }

  static const char* value(const ::assignment2_ros1::UserInputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserInputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_ros1::UserInputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_ros1::UserInputRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.user_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_ROS1_MESSAGE_USERINPUTREQUEST_H
